import type { Locale } from './translations';
const en = { mode: 'Interactive showcase', boundary: 'Fictional sources · Authored reasoning · No live analysis', portfolio: 'Back to portfolio', load: 'Load sample case', previous: 'Previous', next: 'Next step', reset: 'Reset demo', steps: ['Initial report', 'New evidence', 'Contradiction', 'Updated ledger'], narrative: 'Scenario', sources: 'Sources in this revision', graph: 'Reasoning graph', record: 'Case record', rename: 'Rename', archive: 'Archive', restore: 'Restore', remove: 'Delete', save: 'Save', cancel: 'Cancel', title: 'Case title', number: 'Case number', options: 'Case options', language: 'Language', empty: 'Load a sample case to explore the evidence ledger.', storage: 'Changes are saved in this browser.', memory: 'Browser storage is unavailable. Changes last for this visit.', openCases: 'Open cases', close: 'Close', deleteQuestion: 'Delete this local demo copy?', export: 'Export', step: 'Step' };
const text: Record<Locale, typeof en> = {
  en,
  vi: { mode: 'Showcase tương tác', boundary: 'Nguồn hư cấu · Lập luận soạn sẵn · Không phân tích trực tiếp', portfolio: 'Về portfolio', load: 'Mở hồ sơ mẫu', previous: 'Bước trước', next: 'Bước tiếp', reset: 'Đặt lại demo', steps: ['Báo cáo ban đầu', 'Bằng chứng mới', 'Phát hiện mâu thuẫn', 'Cập nhật sổ cái'], narrative: 'Kịch bản', sources: 'Nguồn của phiên bản này', graph: 'Đồ thị lập luận', record: 'Hồ sơ', rename: 'Đổi tên', archive: 'Lưu trữ', restore: 'Khôi phục', remove: 'Xóa', save: 'Lưu', cancel: 'Hủy', title: 'Tên hồ sơ', number: 'Mã hồ sơ', options: 'Tùy chọn hồ sơ', language: 'Ngôn ngữ', empty: 'Mở hồ sơ mẫu để khám phá sổ cái bằng chứng.', storage: 'Thay đổi được lưu trong browser này.', memory: 'Không truy cập được bộ nhớ browser. Thay đổi chỉ giữ trong lượt xem này.', openCases: 'Mở danh sách hồ sơ', close: 'Đóng', deleteQuestion: 'Xóa bản demo cục bộ này?', export: 'Xuất', step: 'Bước' },
  es: { mode: 'Demostración interactiva', boundary: 'Fuentes ficticias · Razonamiento preparado · Sin análisis en vivo', portfolio: 'Volver al portafolio', load: 'Cargar caso de ejemplo', previous: 'Anterior', next: 'Siguiente', reset: 'Reiniciar demo', steps: ['Informe inicial', 'Nueva evidencia', 'Contradicción', 'Registro actualizado'], narrative: 'Escenario', sources: 'Fuentes de esta revisión', graph: 'Grafo de razonamiento', record: 'Expediente', rename: 'Renombrar', archive: 'Archivar', restore: 'Restaurar', remove: 'Eliminar', save: 'Guardar', cancel: 'Cancelar', title: 'Título', number: 'Número del caso', options: 'Opciones', language: 'Idioma', empty: 'Carga un caso de ejemplo para explorar el registro.', storage: 'Cambios guardados en este navegador.', memory: 'Sin almacenamiento. Los cambios duran esta visita.', openCases: 'Abrir casos', close: 'Cerrar', deleteQuestion: '¿Eliminar esta copia local?', export: 'Exportar', step: 'Paso' },
  fr: { mode: 'Démonstration interactive', boundary: 'Sources fictives · Raisonnement préparé · Sans analyse en direct', portfolio: 'Retour au portfolio', load: 'Charger un exemple', previous: 'Précédent', next: 'Suivant', reset: 'Réinitialiser', steps: ['Rapport initial', 'Nouvelle preuve', 'Contradiction', 'Registre actualisé'], narrative: 'Scénario', sources: 'Sources de cette révision', graph: 'Graphe de raisonnement', record: 'Dossier', rename: 'Renommer', archive: 'Archiver', restore: 'Restaurer', remove: 'Supprimer', save: 'Enregistrer', cancel: 'Annuler', title: 'Titre', number: 'Numéro du dossier', options: 'Options', language: 'Langue', empty: 'Chargez un exemple pour explorer le registre.', storage: 'Modifications enregistrées dans ce navigateur.', memory: 'Stockage indisponible. Les modifications durent cette visite.', openCases: 'Ouvrir les dossiers', close: 'Fermer', deleteQuestion: 'Supprimer cette copie locale ?', export: 'Exporter', step: 'Étape' },
  'zh-CN': { mode: '交互演示', boundary: '虚构来源 · 预先编写的推理 · 无实时分析', portfolio: '返回作品集', load: '载入示例', previous: '上一步', next: '下一步', reset: '重置演示', steps: ['初始报告', '新增证据', '发现矛盾', '更新台账'], narrative: '场景', sources: '本版本的来源', graph: '推理图', record: '案件记录', rename: '重命名', archive: '归档', restore: '恢复', remove: '删除', save: '保存', cancel: '取消', title: '案件标题', number: '案件编号', options: '案件选项', language: '语言', empty: '载入示例以探索证据台账。', storage: '更改保存在此浏览器中。', memory: '浏览器存储不可用。更改仅在本次访问中保留。', openCases: '打开案件列表', close: '关闭', deleteQuestion: '删除此本地演示副本？', export: '导出', step: '步骤' },
  ja: { mode: 'インタラクティブデモ', boundary: '架空の資料 · 作成済みの推論 · リアルタイム分析なし', portfolio: 'ポートフォリオへ', load: 'サンプルを開く', previous: '前へ', next: '次へ', reset: 'デモをリセット', steps: ['初期報告', '新しい証拠', '矛盾の発見', '台帳の更新'], narrative: 'シナリオ', sources: 'この版の資料', graph: '推論グラフ', record: '案件記録', rename: '名前を変更', archive: 'アーカイブ', restore: '復元', remove: '削除', save: '保存', cancel: 'キャンセル', title: '案件名', number: '案件番号', options: '案件の設定', language: '言語', empty: 'サンプルを開いて証拠台帳を確認してください。', storage: '変更はこのブラウザに保存されます。', memory: 'ストレージを利用できません。変更は今回の閲覧中のみ保持されます。', openCases: '案件一覧を開く', close: '閉じる', deleteQuestion: 'このローカルデモを削除しますか？', export: 'エクスポート', step: 'ステップ' },
};
export const showcaseText = (locale: Locale) => text[locale];
